#!/bin/bash
set -e

#/etc/init.d/php5-fpm start
#/etc/init.d/nginx start
/etc/init.d/shibd start

# Apache gets grumpy about PID files pre-existing
rm -f /usr/local/apache2/logs/httpd.pid

exec apachectl -DFOREGROUND
